### ISSUE TITLE
CreateFile returns Handle -1

### ISSUE THREAD

**Issue by berthendrickx** [bbeardsley/BuzzIO#4]
Hi,

The device path is detected, but the Initialise function of HIDDevice.cs the CreateFile function returns -1 as handle. The controllers work fine in the Windows control panel.

![image](https://cloud.githubusercontent.com/assets/9867885/24668110/ff6f0290-1965-11e7-8873-9120f19f712f.png)

I'm using Visual Studio Community 2015 and the latest version of the code.
My system is Windows 10 64 bit.

Kind regards,
Bert

**Comment by dickxpe** [comment]
Same problem, any news on this?

**Comment by bbeardsley** [comment]
What does GetLastError return after you get the -1?  Are you building 32bit or 64bit?

**Comment by dickxpe** [comment]
1008

**Comment by dickxpe** [comment]
i'm building x86, if i change it to x64, when i run the application the following line of code returns null in the HIDDevice class:  line 236: var strDevicePath = GetDevicePath(hInfoSet, ref oInterface);

**Comment by jspraul** [comment]
Comments on the original article mention 64-bit fixes:

http://www.developerfusion.com/article/84338/making-usb-c-friendly/

> 
> I found a bug for 64-bit systems:You need to check to size of the DeviceInterfaceDetailData, because on 64-bit its 8 and on 32-bit systems its 5.
> 
> HIDDevice.cs
> 
> Line 191, should be replaced by:
> 
>                 if (Marshal.SizeOf(typeof(IntPtr)) == 8)
>                 {
>                     oDetail.Size = 8; //For 64 bit.
>                 }
>                 else
>                 {
>                     oDetail.Size = 5; // hardcoded to 5! Sorry, but this works and trying more future proof versions by setting the size to the struct sizeof failed miserably. If you manage to sort it, mail me! Thx
>                 }
> 
> And in HIDDevice.cs the variable Reserved should be of type IntPtr.
> 
> Line 36, should be replaced by:
> 
>             public IntPtr Reserved;

> Look like this was moved to Win32USB.cs. I changed it to look like this
> 
>         protected struct DeviceInterfaceData
>         {
>             public Int32 Size;
>             public Guid InterfaceClassGuid;
>             public Int32 Flags;
>             public IntPtr Reserved;
>         }

**Comment by Oberown** [comment]
Hello,

I made the change.
I'm on VS 2019, and framework 4.72

I have this exception:
When Msg:Failed to create device file WinEr:00000020
oNewDevice.Initialise(strDevicePath);
strDevicePath = \?\hid#vid_054c&pid_1000#6&21d32633&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
in FindDevices

I compile in x64

**Comment by bbeardsley** [comment]
I've only built in x86 - happy to have a PR for x64

**Comment by bbeardsley** [comment]
For the 1008 error - see https://stackoverflow.com/questions/33473085/loadlibrary-error-code-1008

**Comment by Oberown** [comment]
If you have a little program who have work with windows 10.
Please can i download it, to test on my desktop please ?

**Comment by Oberown** [comment]
I rewrite the library with the package HidLabrary.
